<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="My Website">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="../css/main.css">
        <link rel="stylesheet" href="../css/bootstrap-4.1.1-dist/css/bootstrap.min.css"/>
        <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
        <title>Jeffrey Feng - {{page.title}}</title>
        <script src="../css/bootstrap-4.1.1-dist/js/bootstrap.min.js"></script>
        <link rel="shortcut icon" type="image/x-icon" href="../assets/images/favicon.png">
</head>
    
    