<nav class="navbar navbar-expand-lg">
    <div class="container">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsedNav" aria-expanded="false"></button>
            
        <div class="navbar-collapse collapse" id="collapsedNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a></li>
            <li class="nav-item">
                <a class="nav-link" href="/portfolio/">Portfolio</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/photos/">Photos</a>
            </li>
        

            <li class="nav-item">
                <a class="nav-link" href="/resume/">Resume</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/contact/">About</a>
            </li>
        </ul>
        </div>
        
    </div>
</nav>

